### ISSUE TITLE
OCP 4.1 Binaries not available for Azure

### ISSUE THREAD

**Issue by harshjay04** [JuozasA/ocp4-azure-upi#1]
Unfortunately the link provided for binaries are pointing back to 4.2 dev preview binaries and i was unable to go further , can you help guide me to get the correct binaries.
 
https://blog.openshift.com/openshift-4-1-upi-environment-deployment-on-microsoft-azure-cloud/

**Comment by JuozasA** [comment]
Hi @harshjay04 

try this mirror: http://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.0/

**Comment by JuozasA** [comment]
@harshjay04 I added additional step. Since 4.2 is released. You have to download both, 4.1 and 4.2 (or latest available) installers. Generate install-config.yaml with the latest or 4.2 installer. Manifests and Ignition configs must be created with 4.1 installer. That way bootstrap will pull 4.1 packages.
